server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml

#日志
logging:
  level:
    root: warn
    com.zhouchb.blog: info
  file:
    path: log/blog-pro.log

