spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations:  classpath:mapper/*.xml

#日志
logging:
  level:
    root: info
    com.zhouchb.blog-dev: debug
  file:
    path: log/blog-dev.log
